title: Muhammad Jabbar # your name (or website title) here
logo: "/images/14538.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With over 8 years of experience in Full Stack development, I bring a keen attention to detail and excel in collaborative environments. My expertise spans front-end technologies such as HTML, CSS, JavaScript, and frameworks like React, Vue.js, Nuxt and tailwind as well as back-end technologies including Node.js, Express, Nest, Laravel, Django and databases like MongoDB and SQL. I have a proven track record of delivering high-quality, scalable web applications and thrive in agile teams where communication and cooperation drive project success.
  <br><br>
  Whether working as a team player or an individual contributor, I consistently deliver exceptional results.
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
